# Generated by Django 5.2.17 on 2026-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weisswurstrunde', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'event_type']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WEISSWURST', 'Weißwurst'), ('LEBERKAESE', 'Leberkäse')], default='WEISSWURST', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='event_type',
            field=models.CharField(choices=[('WEISSWURST', 'Weißwurst'), ('LEBERKAESE', 'Leberkäse')], default='WEISSWURST', max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('date', 'event_type'), name='one_event_per_type_date'),
        ),
    ]
