# Generated by Django 5.2.17 on 2026-09-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weisswurstrunde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
